package com.trend.feature_common.utils

import com.trend.feature_common.models.CountriesCellphoneDataModel

class CountriesDataHelper {
    companion object {
        var countries: ArrayList<CountriesCellphoneDataModel> = arrayListOf()

        fun getCountriesData(): ArrayList<CountriesCellphoneDataModel>{
            countries.clear()
            countries.add((CountriesCellphoneDataModel("+57", "CO", "Colombia")))
            countries.add((CountriesCellphoneDataModel("+506", "CR", "Costa Rica")))
            countries.add((CountriesCellphoneDataModel("+503","SV", "El Salvador")))
            countries.add((CountriesCellphoneDataModel("+502","GT", "Guatemala")))
            countries.add((CountriesCellphoneDataModel("+504","HN", "Honduras")))
            countries.add((CountriesCellphoneDataModel("+52","MX", "México")))
            countries.add((CountriesCellphoneDataModel("+505","NI", "Nicaragua")))
            countries.add((CountriesCellphoneDataModel("+507","PA", "Panamá")))
            countries.add((CountriesCellphoneDataModel("+1","PR", "Puerto Rico")))
            countries.add((CountriesCellphoneDataModel("+1","DO", "Republica Dominicana")))
            countries.add((CountriesCellphoneDataModel("+591","BO", "Bolivia")))
            countries.add((CountriesCellphoneDataModel("+54","AR", "Argentina")))
            countries.add((CountriesCellphoneDataModel("+595","PY", "Paraguay")))
            countries.add((CountriesCellphoneDataModel("+51","PE", "Perú")))
            countries.add((CountriesCellphoneDataModel("+598","UY", "Uruguay")))
            countries.add((CountriesCellphoneDataModel("+58","VE", "Venezuela")))

            /*countries.add((CustomSpinnerModel("93", "AF")))
            countries.add((CustomSpinnerModel("355", "AL")))
            countries.add((CustomSpinnerModel("213", "DZ")))
            countries.add((CustomSpinnerModel("244", "AO")))
            countries.add((CustomSpinnerModel("54", "AR")))
            countries.add((CustomSpinnerModel("474", "AM")))
            countries.add((CustomSpinnerModel("374", "AM")))
            countries.add((CustomSpinnerModel("297", "AW")))
            countries.add((CustomSpinnerModel("61", "AU")))
            countries.add((CustomSpinnerModel("43", "AT")))
            countries.add((CustomSpinnerModel("994", "AZ")))
            countries.add((CustomSpinnerModel("973", "BH")))
            countries.add((CustomSpinnerModel("880", "BD")))
            countries.add((CustomSpinnerModel("994", "BH")))
            countries.add((CustomSpinnerModel("375", "BY")))
            countries.add((CustomSpinnerModel("32", "BE")))
            countries.add((CustomSpinnerModel("501", "BZ")))
            countries.add((CustomSpinnerModel("229", "BJ")))
            countries.add((CustomSpinnerModel("975", "BT")))
            countries.add((CustomSpinnerModel("591", "BO")))
            countries.add((CustomSpinnerModel("387", "BA")))
            countries.add((CustomSpinnerModel("267", "BW")))
            countries.add((CustomSpinnerModel("55", "BR")))
            countries.add((CustomSpinnerModel("673", "BN")))
            countries.add((CustomSpinnerModel("359", "BG")))
            countries.add((CustomSpinnerModel("226", "BF")))
            countries.add((CustomSpinnerModel("95", "MM")))
            countries.add((CustomSpinnerModel("257", "BI")))
            countries.add((CustomSpinnerModel("855", "KH")))
            countries.add((CustomSpinnerModel("237", "CM")))
            countries.add((CustomSpinnerModel("1", "CA")))
            countries.add((CustomSpinnerModel("238", "CV")))
            countries.add((CustomSpinnerModel("236", "CF")))
            countries.add((CustomSpinnerModel("235", "TD")))
            countries.add((CustomSpinnerModel("56", "CL")))
            countries.add((CustomSpinnerModel("86", "CN")))
            countries.add((CustomSpinnerModel("61", "CX")))
            countries.add((CustomSpinnerModel("61", "CC")))

            countries.add((CustomSpinnerModel("269", "KM")))
            countries.add((CustomSpinnerModel("242", "CG")))
            countries.add((CustomSpinnerModel("243", "CD")))
            countries.add((CustomSpinnerModel("682", "CK")))

            countries.add((CustomSpinnerModel("385", "HR")))
            countries.add((CustomSpinnerModel("53", "CU")))
            countries.add((CustomSpinnerModel("357", "CY")))
            countries.add((CustomSpinnerModel("420", "CZ")))
            countries.add((CustomSpinnerModel("45", "DK")))
            countries.add((CustomSpinnerModel("253", "DJ")))
            countries.add((CustomSpinnerModel("670","TL")))
            countries.add((CustomSpinnerModel("593","EC")))
            countries.add((CustomSpinnerModel("20","EG")))

            countries.add((CustomSpinnerModel("240","GQ")))
            countries.add((CustomSpinnerModel("291","ER")))
            countries.add((CustomSpinnerModel("372","EE")))
            countries.add((CustomSpinnerModel("251","ET")))
            countries.add((CustomSpinnerModel("500","FK")))
            countries.add((CustomSpinnerModel("298","FO")))
            countries.add((CustomSpinnerModel("679","FJ")))
            countries.add((CustomSpinnerModel("358","FI")))
            countries.add((CustomSpinnerModel("33","FR")))
            countries.add((CustomSpinnerModel("689","PF")))
            countries.add((CustomSpinnerModel("241","GA")))
            countries.add((CustomSpinnerModel("220","GM)")))
            countries.add((CustomSpinnerModel("995","GE")))
            countries.add((CustomSpinnerModel("49","DE")))
            countries.add((CustomSpinnerModel("233","GH")))
            countries.add((CustomSpinnerModel("350","GI")))
            countries.add((CustomSpinnerModel("30","GR")))
            countries.add((CustomSpinnerModel("299","GL")))

            countries.add((CustomSpinnerModel("224","GN")))
            countries.add((CustomSpinnerModel("245","GW")))
            countries.add((CustomSpinnerModel("592","GY")))
            countries.add((CustomSpinnerModel("509","HT")))

            countries.add((CustomSpinnerModel("852","HK")))
            countries.add((CustomSpinnerModel("36","HU")))
            countries.add((CustomSpinnerModel("91","IN")))
            countries.add((CustomSpinnerModel("62","ID")))
            countries.add((CustomSpinnerModel("98","IR")))
            countries.add((CustomSpinnerModel("964","IQ")))
            countries.add((CustomSpinnerModel("353","IE")))
            countries.add((CustomSpinnerModel("44","IM")))
            countries.add((CustomSpinnerModel("972","IL")))
            countries.add((CustomSpinnerModel("39","IT")))
            countries.add((CustomSpinnerModel("225","CI")))
            countries.add((CustomSpinnerModel("81","JP")))
            countries.add((CustomSpinnerModel("962","JO")))
            countries.add((CustomSpinnerModel("7","KZ")))
            countries.add((CustomSpinnerModel("254","KE")))
            countries.add((CustomSpinnerModel("686","KI")))
            countries.add((CustomSpinnerModel("965","KW")))
            countries.add((CustomSpinnerModel("996","KG")))
            countries.add((CustomSpinnerModel("856","LA")))
            countries.add((CustomSpinnerModel("371","LV")))
            countries.add((CustomSpinnerModel("961","LB")))
            countries.add((CustomSpinnerModel("266","LS")))
            countries.add((CustomSpinnerModel("231","LR")))
            countries.add((CustomSpinnerModel("218","LY")))
            countries.add((CustomSpinnerModel("423","LI")))
            countries.add((CustomSpinnerModel("370","LT")))
            countries.add((CustomSpinnerModel("352","LU")))
            countries.add((CustomSpinnerModel("853","MO")))
            countries.add((CustomSpinnerModel("389","MK")))
            countries.add((CustomSpinnerModel("261","MG")))
            countries.add((CustomSpinnerModel("265","MW")))
            countries.add((CustomSpinnerModel("60","MY")))
            countries.add((CustomSpinnerModel("960","MV")))
            countries.add((CustomSpinnerModel("223","ML")))
            countries.add((CustomSpinnerModel("356","MT")))
            countries.add((CustomSpinnerModel("692","MH")))
            countries.add((CustomSpinnerModel("222","MR")))
            countries.add((CustomSpinnerModel("230","MU")))
            countries.add((CustomSpinnerModel("262","YT")))

            countries.add((CustomSpinnerModel("691","FM")))
            countries.add((CustomSpinnerModel("373","MD")))
            countries.add((CustomSpinnerModel("377","MC")))
            countries.add((CustomSpinnerModel("976","MN")))
            countries.add((CustomSpinnerModel("382","ME")))
            countries.add((CustomSpinnerModel("212","MA")))
            countries.add((CustomSpinnerModel("258","MZ")))
            countries.add((CustomSpinnerModel("264","NA")))
            countries.add((CustomSpinnerModel("674","NR")))
            countries.add((CustomSpinnerModel("977","NP")))
            countries.add((CustomSpinnerModel("31","NL")))
            countries.add((CustomSpinnerModel("599","AN")))
            countries.add((CustomSpinnerModel("687","NC")))
            countries.add((CustomSpinnerModel("64","NZ")))

            countries.add((CustomSpinnerModel("227","NE")))
            countries.add((CustomSpinnerModel("234","NG")))
            countries.add((CustomSpinnerModel("683","NU")))
            countries.add((CustomSpinnerModel("850","KP")))
            countries.add((CustomSpinnerModel("47","NO")))
            countries.add((CustomSpinnerModel("968","OM")))
            countries.add((CustomSpinnerModel("92","PK")))
            countries.add((CustomSpinnerModel("680","PW")))

            countries.add((CustomSpinnerModel("675","PG")))
            countries.add((CustomSpinnerModel("595","PY")))
            countries.add((CustomSpinnerModel("51","PE")))
            countries.add((CustomSpinnerModel("63","PH")))
            countries.add((CustomSpinnerModel("870","PN")))
            countries.add((CustomSpinnerModel("48","PL")))
            countries.add((CustomSpinnerModel("351","PT")))
            countries.add((CustomSpinnerModel("1","PR")))
            countries.add((CustomSpinnerModel("974","QA")))
            countries.add((CustomSpinnerModel("40","RO")))
            countries.add((CustomSpinnerModel("7","RU")))
            countries.add((CustomSpinnerModel("250","RW")))
            countries.add((CustomSpinnerModel("590","BL")))
            countries.add((CustomSpinnerModel("685","WS")))
            countries.add((CustomSpinnerModel("378","SM")))
            countries.add((CustomSpinnerModel("239","ST")))
            countries.add((CustomSpinnerModel("966","SA")))
            countries.add((CustomSpinnerModel("221","SN")))
            countries.add((CustomSpinnerModel("381","RS")))
            countries.add((CustomSpinnerModel("248","SC")))
            countries.add((CustomSpinnerModel("232","SL")))
            countries.add((CustomSpinnerModel("65","SG")))
            countries.add((CustomSpinnerModel("421","SK")))
            countries.add((CustomSpinnerModel("386","SI")))
            countries.add((CustomSpinnerModel("677","SB")))
            countries.add((CustomSpinnerModel("252","SO")))
            countries.add((CustomSpinnerModel("27","ZA")))
            countries.add((CustomSpinnerModel("82","KR")))
            countries.add((CustomSpinnerModel("34","ES")))
            countries.add((CustomSpinnerModel("94","LK")))
            countries.add((CustomSpinnerModel("290","SH")))
            countries.add((CustomSpinnerModel("508","PM")))
            countries.add((CustomSpinnerModel("249","SD")))
            countries.add((CustomSpinnerModel("597","SR")))
            countries.add((CustomSpinnerModel("268","SZ")))
            countries.add((CustomSpinnerModel("46","SE")))
            countries.add((CustomSpinnerModel("41","CH")))
            countries.add((CustomSpinnerModel("963","SY")))
            countries.add((CustomSpinnerModel("886","TW")))
            countries.add((CustomSpinnerModel("992","TJ")))
            countries.add((CustomSpinnerModel("255","TZ")))
            countries.add((CustomSpinnerModel("66","TH")))
            countries.add((CustomSpinnerModel("228","TG")))
            countries.add((CustomSpinnerModel("690","TK")))
            countries.add((CustomSpinnerModel("676","TO")))
            countries.add((CustomSpinnerModel("216","TN")))
            countries.add((CustomSpinnerModel("90","TR")))
            countries.add((CustomSpinnerModel("993","TM")))
            countries.add((CustomSpinnerModel("688","TV")))
            countries.add((CustomSpinnerModel("971","AE")))
            countries.add((CustomSpinnerModel("256","UG")))
            countries.add((CustomSpinnerModel("44","GB")))
            countries.add((CustomSpinnerModel("380","UA")))
            countries.add((CustomSpinnerModel("598","UY")))
            countries.add((CustomSpinnerModel("1","US")))
            countries.add((CustomSpinnerModel("998","UZ")))
            countries.add((CustomSpinnerModel("678","VU")))
            countries.add((CustomSpinnerModel("39","VA")))
            countries.add((CustomSpinnerModel("58","VE")))
            countries.add((CustomSpinnerModel("84","VN")))
            countries.add((CustomSpinnerModel("681","WF")))
            countries.add((CustomSpinnerModel("967","YE")))
            countries.add((CustomSpinnerModel("260","ZM")))
            countries.add((CustomSpinnerModel("263","ZW")))*/
            return countries
        }
    }
}